#pragma once
#define FALSE 0
#define TRUE 1

#define WINDOW_TITLE "Chip-8 Emulator"
#define WINDOW_WIDTH 960
#define WINDOW_HEIGHT 480

#define SCREEN_WIDTH 64
#define SCREEN_HEIGHT 32

#define CYCLES 500
#define FPS 60
#define PIXEL_WIDTH WINDOW_WIDTH/SCREEN_WIDTH
#define PIXEL_HEIGHT WINDOW_HEIGHT/SCREEN_HEIGHT
#define PIXEL_COUNT SCREEN_WIDTH*SCREEN_HEIGHT

#define MEMORY_SIZE 4096
#define STACK_SIZE 16
#define REGISTER_COUNT 16

#define CHARACTER_SET_SIZE 80

#define MEMORY_INTERPRETER_START 0x0
#define MEMORY_PROGRAM_START 0x200

#define KEYBOARD_COUNT 16

#define SOUND_SAMPLE_RATE 44100
#define SOUND_FREQ 440